#include <czmq.h>
#include "Stats.c"
#include <time.h>
#include "Summary_builder.h" // Generated by `flatcc`.
#include "flatbuffers_common_builder.h"

#undef ns
#define ns(x) FLATBUFFERS_WRAP_NAMESPACE(Test, x) // specified in the schema


//Reading config file 
char* configFileName = "conf/edge.config";
//zhashx_t *hashbatchfreq;
zhashx_t *hashexpirytime;
zhashx_t *hashstatsobject;
zloop_t *loop;
zsock_t *sub;

//This function is returning current timestamp in milli seconds
unsigned long long getTimestampInMillis(){
	struct timeval tv;
	gettimeofday(&tv, NULL);
	return (unsigned long long)(tv.tv_sec) * 1000 + (unsigned long long)(tv.tv_usec) / 1000;
}

//This function is recieving messages over port 9000
int zmq_recieve(zloop_t *loop, zsock_t *sub, void *arg){
	char* msg = zstr_recv(sub);
	//printf("%s \n", msg);
	char* topic = strtok(strdup(msg), ",");
	char* content = strtok(NULL,"\0");
	if(zhashx_lookup(hashstatsobject, topic) != NULL){
		Stats *temp = zhashx_lookup(hashstatsobject, topic);
		temp->add(content,temp);
	}
}

int checking_expiry(){
	zlistx_t *exp = zhashx_keys(hashexpirytime);
	char *tmpid = (char*)zlistx_first(exp);
	printf("%s\n",tmpid);
	while(tmpid != NULL){
		printf("%s\n",tmpid);
		unsigned long ts = (unsigned long) (zhashx_lookup(hashexpirytime, tmpid));
		unsigned long current = getTimestampInMillis() / 1000;
		printf("======%lu=================%lu=======\n",ts,current);
		if(current >= ts){
			char * _ = strtok(strdup(tmpid), "/");
			char * __ = strtok(NULL, "/");
			char * ___ = strtok(NULL, "/");
			int tmp1 = atoi(___);
			unsigned long * tmp2 = (unsigned long *) (ts +  (tmp1 * 60));
			zhashx_update(hashexpirytime, tmpid, tmp2);
			Stats *tmpob = zhashx_lookup(hashstatsobject, tmpid);
			uint8_t* b = tmpob->getSummary(tmpob);
			ns(Summary_table_t) Summary = ns(Summary_as_root(b));
			double Rms = ns(Summary_Rms(Summary));
			double Kurtosis = ns(Summary_Kurtosis(Summary));
			double Skewness = ns(Summary_Skewness(Summary));
			double Variance = ns(Summary_Variance(Summary));
			double Mean = ns(Summary_Mean(Summary));
			double min = ns(Summary_min(Summary));
			double max = ns(Summary_max(Summary));
			double count = ns(Summary_count(Summary));
			double sumOfSquare = ns(Summary_sumOfSquare(Summary));
                        double Percentile_2 = ns(Summary_Percentile_2(Summary));
                        double Percentile_5 = ns(Summary_Percentile_5(Summary));
                        double Percentile_10 = ns(Summary_Percentile_10(Summary));
                        double Percentile_20 = ns(Summary_Percentile_20(Summary));
                        double Percentile_40 = ns(Summary_Percentile_40(Summary));
                        double Percentile_50 = ns(Summary_Percentile_50(Summary));
                        double Percentile_60 = ns(Summary_Percentile_60(Summary));
                        double Percentile_80 = ns(Summary_Percentile_80(Summary));
                        double Percentile_90 = ns(Summary_Percentile_90(Summary));
                        double Percentile_95 = ns(Summary_Percentile_95(Summary));
                        double Percentile_98 = ns(Summary_Percentile_98(Summary));
                        double Percentile_99 = ns(Summary_Percentile_99(Summary));
                        double Percentile_100 = ns(Summary_Percentile_100(Summary));
                        double Percentile_98_2 = ns(Summary_Percentile_98_2(Summary));
                        double Percentile_95_5 = ns(Summary_Percentile_95_5(Summary));
                        double Percentile_95_10 = ns(Summary_Percentile_95_10(Summary));
                        double Percentile_80_20 = ns(Summary_Percentile_80_20(Summary));
                        double Percentile_60_40 = ns(Summary_Percentile_60_40(Summary));
                        double Crest = ns(Summary_Crest(Summary));
			printf("\nRms : %f",Rms);
			printf("\nKurtosis : %f",Kurtosis);
			printf("\nSkewness : %f",Skewness);
			printf("\nVariance : %f",Variance);
			printf("\nMean : %f",Mean);
			printf("\nMin : %f",min);
			printf("\nMax : %f",max);
			printf("\nCount : %f",count);
			printf("\nSum of Square : %f",sumOfSquare);
                        printf("\nPercentile_2 : %f",Percentile_2);
                        printf("\nPercentile_5 : %f",Percentile_5);
                        printf("\nPercentile_10 : %f",Percentile_10);
                        printf("\nPercentile_20 : %f",Percentile_20);
                        printf("\nPercentile_40: %f",Percentile_40);
                        printf("\nPercentile_50 : %f",Percentile_50);
                        printf("\nPercentile_60 : %f",Percentile_60);
                        printf("\nPercentile_80 : %f",Percentile_80);
                        printf("\nPercentile_90 : %f",Percentile_90);
                        printf("\nPercentile_95 : %f",Percentile_95);
                        printf("\nPercentile_98 : %f",Percentile_98);
                        printf("\nPercentile_99 : %f",Percentile_99);
                        printf("\nPercentile_100 : %f",Percentile_100);
                        printf("\nPercentile_98_2 : %f",Percentile_98_2);
                        printf("\nPercentile_95_5 : %f",Percentile_95_5);
                        printf("\nPercentile_95_10 : %f",Percentile_95_10);
                        printf("\nPercentile_80_20 : %f",Percentile_80_20);
                        printf("\nPercentile_60_40 : %f",Percentile_60_40);
                        printf("\nCrest : %f\n",Crest);
			//double m = tmpob->getCount(tmpob);
			//printf("\n%f\n",m);
		}
		tmpid = (char*)zlistx_next(exp);
	}
}

main(){
	/*
        hashbatchfreq = zhashx_new ();
        assert (hashbatchfreq);
        assert (zhashx_size (hashbatchfreq) == 0);
        assert (zhashx_first (hashbatchfreq) == NULL);
        assert (zhashx_cursor (hashbatchfreq) == NULL);
	*/
	
        hashexpirytime = zhashx_new ();
        assert (hashexpirytime);
        assert (zhashx_size (hashexpirytime) == 0);
        assert (zhashx_first (hashexpirytime) == NULL);
        assert (zhashx_cursor (hashexpirytime) == NULL);

        hashstatsobject = zhashx_new ();
        assert (hashstatsobject);
        assert (zhashx_size (hashstatsobject) == 0);
        assert (zhashx_first (hashstatsobject) == NULL);
        assert (zhashx_cursor (hashstatsobject) == NULL);

	loop = zloop_new ();
        assert (loop);

	sub = zsock_new_pull("tcp://127.0.0.1:9000");
	assert(sub);

	char* line;
        size_t len = 0;
        ssize_t read;
        FILE* file = fopen(configFileName, "r");
        while ((read = getline(&line, &len, file)) != -1){
                if(read != 1){
                        line[strlen(line)-1] = 0;
                        //printf("%s\n", line);
                        char* sid = strtok(strdup(line), "/");
                        char* param = strtok(NULL,"/");
                        char* batchfreq = strtok(NULL,"/");
			char* sliding_window = strtok(NULL,"\0");
			int obatchfreq = atoi(batchfreq);
                        //printf("%s\n", sid);
                        //printf("%s\n", param);
                        //printf("%d\n", obatchfreq);
			char tid[50];
			sprintf(tid,"%s",line);
			unsigned long * calcTimeStmp;
			int tmp = 60 * obatchfreq;
			unsigned long long tmpTimeStmp = getTimestampInMillis() / 1000;
			calcTimeStmp = (unsigned long *) ((tmpTimeStmp) - (tmpTimeStmp % tmp) + (tmp));
			//char *exptime;
			//sprintf(exptime,"%lu",calcTimeStmp);
			printf("-----%s\n", line);
			//Stats *i = (Stats*) malloc(sizeof(Stats));
                        //zhashx_update(hashbatchfreq, tid, batchfreq);
			zhashx_update(hashexpirytime, tid, calcTimeStmp);
			zhashx_update(hashstatsobject, tid, getStatsInstance());
		}
	}
	/*
	if(zhashx_size(hashbatchfreq) > 0 ){
		zlistx_t *keys1 = zhashx_keys(hashbatchfreq);
		printf("%d is the length of current hashbatchfreq\n", zlistx_size(keys1));
		char *ttid = (char*)zlistx_next(keys1);
		printf("\n====>>>>%s--------%s<<<<<====\n",ttid,zhashx_lookup(hashbatchfreq, ttid));
	}
	
	if(zhashx_size(hashexpirytime) > 0 ){
                zlistx_t *keys2 = zhashx_keys(hashexpirytime);
                printf("%d is the length of current hashexpirytime\n", zlistx_size(keys2));
                char *ttid = (char*)zlistx_next(keys2);
                printf("\n====>>>>%s--------%s<<<<<====\n",ttid,zhashx_lookup(hashexpirytime, ttid));
        }
	if(zhashx_size(hashstatsobject) > 0 ){
                zlistx_t *keys3 = zhashx_keys(hashstatsobject);
                printf("%d is the length of current hashstatsobject\n", zlistx_size(keys3));
                char *ttid = (char*)zlistx_next(keys3);
                printf("\n====>>>>%s--------%s<<<<<====\n",ttid,zhashx_lookup(hashstatsobject, ttid));
        }
	*/

	int rcz = zloop_reader (loop, sub, zmq_recieve, NULL);
	assert (rcz == 0);
	
	zloop_timer (loop, 5000, 0, checking_expiry, NULL);

	zloop_start (loop);

	zsock_destroy(&sub);
}
