#include <stdio.h>
#include <math.h>
#include <float.h>
#include <stdlib.h>
#include <string.h>
#include "psquared.h"
#include "Summary_builder.h" // Generated by `flatcc`.
#include "flatbuffers_common_builder.h"

#undef ns
#define ns(x) FLATBUFFERS_WRAP_NAMESPACE(Test, x) // specified in the schema

typedef struct Stats
{
	double n;
	double m1;
	double m2;
	double m3;
	double m4;
	double min;
	double max;
	double count;
	double sumOfSquare;
	Percentile* p2;
	Percentile* p5;
	Percentile* p10;
	Percentile* p20;
	Percentile* p40;
	Percentile* p50;
	Percentile* p60;
	Percentile* p80;
	Percentile* p90;
	Percentile* p95;
	Percentile* p98;
	Percentile* p99;
	Percentile* p100;
	void (*add) (char * , struct Stats *);
	double (*getCount) (struct Stats *);
	double (*getSumOfSquare) (struct Stats *);
	double (*getMean) (struct Stats *);
	double (*getVariance) (struct Stats *);
	double (*getSkewness) (struct Stats *);
	double (*getKurtosis) (struct Stats *);
	double (*getRms) (struct Stats *);
	uint8_t* (*getSummary) (struct Stats *);
}Stats;

void add(char * content , struct Stats * st){
	char *timestamp = strtok(content, ",");
	char *valu = strtok(NULL, "\0");
	double _x = atof(valu);
	st->count = st->count + 1;
	if(st->count == 1){st->min = _x; st->max = _x;}
	if(_x < st->min)
    		st->min = _x;
	if(_x > st->max )
    		st->max = _x;
	double x = _x;
	if(!isnan(x)){
		st->sumOfSquare = st->sumOfSquare + x * x;
		double n1 , delta , delta_n, delta_n2, term1;
		n1 = st->n;
        st->n = st->n + 1;
        delta = x - st->m1;
        delta_n = delta / st->n;
        delta_n2 = delta_n * delta_n;
        term1 = delta * delta_n * n1;
        st->m1 += delta_n;
        st->m4 += term1 * delta_n2 * ( st->n * st->n - 3 * st->n + 3) + 6 * delta_n2 * st->m2 - 4 * delta_n * st->m3;
        st->m3 += term1 * delta_n * ( st->n - 2) - 3 * delta_n * st->m2;
        st->m2 += term1;
	}
	st->p2->accept_value(x,st->p2);
	st->p5->accept_value(x,st->p5);
	st->p10->accept_value(x,st->p10);
	st->p20->accept_value(x,st->p20);
	st->p40->accept_value(x,st->p40);
	st->p50->accept_value(x,st->p50);
	st->p60->accept_value(x,st->p60);
	st->p80->accept_value(x,st->p80);
	st->p90->accept_value(x,st->p90);
	st->p95->accept_value(x,st->p95);
	st->p98->accept_value(x,st->p98);
	st->p99->accept_value(x,st->p99);
	st->p100->accept_value(x,st->p100);
}

double getCount(struct Stats * st){
	return st->count;
}

double getSumOfSquare(struct Stats * st){
	return st->sumOfSquare;
}

double getMean(struct Stats * st){
	return st->m1;
}

double getVariance(struct Stats * st){
	return st->m2 / ( st->n - 1);
}

double getSkewness(struct Stats * st){
	return sqrt(st->n) * st->m3 / pow(st->m2,1.5);
}

double getKurtosis(struct Stats * st){
	return (st->n * st->m4 / ( st->m2 * st->m2 )) - 3 ;
}

double getRms(struct Stats * st){
	return sqrt(st->sumOfSquare) / st->n;
}

uint8_t* getSummary(struct Stats * st){
	printf("I am returning getSummary.....");
	flatcc_builder_t builder, *B;
	B = &builder;
	// Initialize the builder object.
	flatcc_builder_init(B);
	uint8_t *buf; // raw buffer used by flatbuffer
	size_t size; // the size of the flatbuffer
	ns(Summary_start_as_root(B));
	ns(Summary_Rms_add(B, st->getRms(st)));
	ns(Summary_Kurtosis_add(B, st->getKurtosis(st)));
	ns(Summary_Skewness_add(B, st->getSkewness(st)));
	ns(Summary_Variance_add(B, st->getVariance(st)));
	ns(Summary_Mean_add(B, st->getMean(st)));
	ns(Summary_min_add(B, st->min));
	ns(Summary_max_add(B, st->max));
	ns(Summary_count_add(B, st->count));
	ns(Summary_sumOfSquare_add(B, st->sumOfSquare));
	ns(Summary_Percentile_2_add(B, st->p2->getPValue(st->p2)));
	ns(Summary_Percentile_5_add(B, st->p5->getPValue(st->p5)));
	ns(Summary_Percentile_10_add(B, st->p10->getPValue(st->p10)));
	ns(Summary_Percentile_20_add(B, st->p20->getPValue(st->p20)));
	ns(Summary_Percentile_40_add(B, st->p40->getPValue(st->p40)));
	ns(Summary_Percentile_50_add(B, st->p50->getPValue(st->p50)));
	ns(Summary_Percentile_60_add(B, st->p60->getPValue(st->p60)));
	ns(Summary_Percentile_80_add(B, st->p80->getPValue(st->p80)));
	ns(Summary_Percentile_90_add(B, st->p90->getPValue(st->p90)));
	ns(Summary_Percentile_95_add(B, st->p95->getPValue(st->p95)));
	ns(Summary_Percentile_98_add(B, st->p98->getPValue(st->p98)));
	ns(Summary_Percentile_99_add(B, st->p99->getPValue(st->p99)));
	ns(Summary_Percentile_100_add(B, st->p100->getPValue(st->p100)));
	ns(Summary_Percentile_98_2_add(B, (st->p98->getPValue(st->p98) / st->p2->getPValue(st->p2))));
	ns(Summary_Percentile_95_5_add(B, (st->p95->getPValue(st->p95) / st->p5->getPValue(st->p5))));
	ns(Summary_Percentile_95_10_add(B, (st->p95->getPValue(st->p95) / st->p10->getPValue(st->p10))));
	ns(Summary_Percentile_80_20_add(B, (st->p80->getPValue(st->p80) / st->p20->getPValue(st->p20))));
	ns(Summary_Percentile_60_40_add(B, (st->p60->getPValue(st->p60) / st->p40->getPValue(st->p40))));
	ns(Summary_Crest_add(B, (st->p95->getPValue(st->p95) / st->getRms(st))));
	ns(Summary_end_as_root(B));
	buf = flatcc_builder_finalize_buffer(B, &size);
	return buf;
}

Stats * getStatsInstance(){
	Stats *obj = malloc(sizeof(Stats));
	obj->add = add;
	obj->getCount = getCount;
	obj->getSumOfSquare = getSumOfSquare;
	obj->getMean = getMean;
	obj->getVariance = getVariance;
	obj->getSkewness = getSkewness;
	obj->getKurtosis = getKurtosis;
	obj->getRms = getRms;
	obj->getSummary = getSummary;
	obj->p2 = makeInstance();
	obj->p2->psq(0.02,obj->p2);
	obj->p5 = makeInstance();
        obj->p5->psq(0.05,obj->p5);
	obj->p10 = makeInstance();
        obj->p10->psq(0.10,obj->p10);
	obj->p20 = makeInstance();
        obj->p20->psq(0.20,obj->p20);
	obj->p40 = makeInstance();
        obj->p40->psq(0.40,obj->p40);
	obj->p50 = makeInstance();
        obj->p50->psq(0.50,obj->p50);
	obj->p60 = makeInstance();
        obj->p60->psq(0.60,obj->p60);
	obj->p80 = makeInstance();
        obj->p80->psq(0.80,obj->p80);
	obj->p90 = makeInstance();
        obj->p90->psq(0.90,obj->p90);
	obj->p95 = makeInstance();
        obj->p95->psq(0.95,obj->p95);
	obj->p98 = makeInstance();
        obj->p98->psq(0.98,obj->p98);
	obj->p99 = makeInstance();
        obj->p99->psq(0.99,obj->p99);
	obj->p100 = makeInstance();
        obj->p100->psq(1.00,obj->p100);
	return obj;
}

/*
json_object getSummary(char * Dictionary.Statistics, struct Stats * st){
	Dictionary.Statistics Statis;
	int l= sizeof(Statis)/sizeof(char*);
	int i;
	json_object * ret = json_object_new_object();
	for(i=0;i<l;i++)
	{
		switch(Statis[i])
		{
			case MIN:
				json_object_object_add(ret,Statis[i],st->min);
			break;
			case MAX:
				json_object_object_add(ret,Statis[i],st->max);
			break;
			case MEAN:
				st.getMean=getMean;
				json_object_object_add(ret,Statis[i],st.getMean(&st));
			break;
			case VARIANCE:
				st.getVariance=getVariance;
				json_object_object_add(ret,Statis[i],st.getVariance(&st));
			break;
			case SKEWNESS:
				st.getSkewness=getSkewness;
				json_object_object_add(ret,Statis[i],st.getSkewness(&st));
			break;
			case KURTOSOS:
				st.getKurtosis=getKurtosis;
				json_object_object_add(ret,Statis[i],st.getKurtosis(&st));
			break;
			case RMS:
				st.getRms=getRms;
				json_object_object_add(ret,Statis[i],st.getRms(&st));
			break;
		}
	}
	return json_object_to_json_string(ret);
}
*/
